trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: sftpupload@1
  inputs:
    sourceFolder: '$(build.sourcesDirectory)'
    contents: '**'
    targetFolder: '/home/u578789532/domains/praveenkanumuri.com/public_html/TestProject'
    host: '153.92.6.54'
    port: '65002'
    username: 'u578789532'
    password: '9440677784@pP'
    cleanTargetFolder: true
    